/**
 * Build an inlined @font-face stylesheet for the share card.
 *
 * Why this exists: html-to-image serialises the DOM into an SVG
 * foreignObject and rasterises it. Fonts loaded from a <link> to Google
 * are not part of that serialisation, so the browser renders the preview
 * correctly and then exports a PNG in Times New Roman. The only reliable
 * fix is to have the font bytes already in the document as base64.
 *
 * Only the `latin` subset is taken. The vietnamese and latin-ext subsets
 * roughly triple the payload for glyphs the card will not use.
 *
 *   node scripts/embed-fonts.mjs
 *
 * Writes src/fonts.css. Re-run only when the weights change; the output
 * is committed so a clean checkout builds without network access.
 */

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// Card typography only. The app shell keeps using the <link> tag; this
// payload is for the offscreen render node, where correctness matters
// more than a few hundred kilobytes.
const FAMILIES = [
  "Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600",
  "Inter:wght@400;500;600",
];

const url =
  "https://fonts.googleapis.com/css2?" +
  FAMILIES.map((f) => `family=${f}`).join("&") +
  "&display=swap";

const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();

// Google emits one @font-face per subset, each preceded by a /* subset */
// comment. Keep the latin ones and drop the rest.
// Match "/* latin */ @font-face { ... }" exactly, not latin-ext or
// vietnamese. The subset label is the only thing distinguishing them.
const blocks = [
  ...css.matchAll(/\/\*\s*latin\s*\*\/\s*(@font-face\s*\{[^}]+\})/g),
].map((m) => m[1]);
if (blocks.length === 0) throw new Error("no latin subsets found in the CSS");

let out = `/* Generated by scripts/embed-fonts.mjs. Do not edit by hand.
   Fonts: Fraunces and Inter, latin subset, base64 inlined so canvas
   export does not fall back to a system serif. */\n\n`;

// Both families are variable fonts, so Google serves the SAME woff2 for
// every weight requested. Emitting one face per weight downloads and
// inlines identical bytes three times over: 455 KB where 152 KB does the
// same job. Dedupe by URL and declare a weight range instead, which is
// what a variable font wants anyway.
const byUrl = new Map();
for (const face of blocks) {
  const u = face.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  if (!u) continue;
  const family = /font-family:\s*'([^']+)'/.exec(face)?.[1];
  if (!byUrl.has(u)) byUrl.set(u, { family, weights: [] });
  byUrl.get(u).weights.push(Number(/font-weight:\s*(\d+)/.exec(face)?.[1]));
}

let total = 0;
for (const [u, { family, weights }] of byUrl) {
  const bytes = new Uint8Array(
    await (await fetch(u, { headers: { "User-Agent": UA } })).arrayBuffer()
  );
  total += bytes.length;
  const b64 = Buffer.from(bytes).toString("base64");
  const range = `${Math.min(...weights)} ${Math.max(...weights)}`;
  console.log(
    `  ${family}  weights ${range}  ${(bytes.length / 1024).toFixed(0)} KB` +
    ` (one file, was serving ${weights.length}x)`
  );

  out +=
    `@font-face {\n` +
    `  font-family: '${family}';\n` +
    `  font-style: normal;\n` +
    `  font-weight: ${range};\n` +
    `  font-display: block;\n` +
    `  src: url(data:font/woff2;base64,${b64}) format('woff2');\n` +
    `}\n\n`;
}

const dest = resolve(dirname(fileURLToPath(import.meta.url)), "../src/fonts.css");
writeFileSync(dest, out);
console.log(
  `\n${blocks.length} faces, ${(total / 1024).toFixed(0)} KB raw ` +
  `-> ${(out.length / 1024).toFixed(0)} KB base64`
);
console.log(`wrote ${dest}`);
